[theme]
primaryColor = "#16c47f"
backgroundColor = "#07090c"
secondaryBackgroundColor = "#0c1015"
textColor = "#c2cad6"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
